---
title: "LiverMetaIntegratorCode"
author: "E Flynn"
date: "4/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load helper code
```{r helpers}
require('limma')


source("processing_utils.R")
source("meta_utils.R")
```
Load + reformat data 

```{r}
# extract studies for MetaIntegrator - using function specifc for this
resListMI <- lapply(c(1:16), extractStudyMI)

names(resListMI) <- sapply(resListMI, function(x) x$formattedName)
metaObj = list()
metaObj$originalData <- resListMI
checkDataObject(metaObj, "Meta", "Pre-Analysis")

```

```{r}
# running meta-analysis on the full set
metaObj <- runMetaAnalysis(metaObj)
str(metaObj, max.level=2)
metaObj <- filterGenes(metaObj, isLeaveOneOut=TRUE, FDRThresh = 0.05, effectSizeThresh = 0.3)
save(metaObj, file="../data/metaObj.RData")
filterRes <-summarizeFilterResults(metaObj, getMostRecentFilter(metaObj))
# --> 74 negative, 60 positive

# add labels
upReg <- filterRes$pos
downReg <- filterRes$neg
upReg$key <- rownames(upReg)
downReg$key <- rownames(downReg)
upRegLabeled <- merge(upReg, json.df[json.df$key %in% upReg$key,])
downRegLabeled <- merge(downReg, json.df[json.df$key %in% downReg$key,])

write.csv(upRegLabeled, file="../results/up_regulatedv2.csv", row.names=FALSE, quote=FALSE)
write.csv(downRegLabeled, file="../results/down_regulatedv2.csv", row.names=FALSE, quote=FALSE)

## - look at overlap w/ pharmgkb genes
gene.info <- read.delim("../external_data/pharmgkb_genes.tsv")
dim(gene.info)
colnames(gene.info)
gene.info[gene.info$Has.Variant.Annotation=="Yes",]
vips <- gene.info[gene.info$Is.VIP=="Yes",]
upRegLabeled$gene[upRegLabeled$gene %in% vips$Symbol] # ABCB1
downRegLabeled$gene[downRegLabeled$gene %in% vips$Symbol]  # CYP3A4, SLC22A1
downRegLabeled$key[downRegLabeled$gene %in% vips$Symbol] 

dmets <- read.csv("../external_data/dmets.csv", colClasses="character")
upRegLabeled$gene[upRegLabeled$gene %in% dmets$Gene.Symbol]
downRegLabeled$gene[downRegLabeled$gene %in% dmets$Gene.Symbol]

```

```{r}
# validation???

load("../data/processed/ds17.RData")
sig.keys.disc <- c(upReg$key, downReg$key) # 209 --> 134
sig.keys <- datasetInfo17$keys[(datasetInfo17$keys %in% sig.keys.disc)]
length(sig.keys)
ds17.sm <- datasetInfo17$expr[names(sig.keys),]
sig.keys.in.both <- sig.keys.disc[sig.keys.disc  %in% sig.keys] # 129 out of 134, was 202 out of 209
# group by key
ds17.sm.grouped <- do.call(rbind, lapply(sig.keys.in.both, function(x){
  corres.keys <- names(sig.keys[sig.keys==x]);
  if (length(corres.keys) == 1){
    keep.row <- 1
  } else{
    keep.row <- which.max(abs(rowMeans(datasetInfo17$expr[corres.keys,])))
  }
  return(datasetInfo17$expr[corres.keys[keep.row],])
} ))
rownames(ds17.sm.grouped) <- sig.keys.in.both


lm17 <- lmFit(ds17.sm.grouped) # only look at the data ID'd before
lm17 <- eBayes(lm17)
lm17.tab <- topTable(lm17, number=length(sig.keys.in.both))
lm17.tab.cut <- lm17.tab[lm17.tab$adj.P.Val<0.05,]
nrow(lm17.tab.cut) # 117 out of 129   --- 159 pass threshold (out of 202)
head(lm17.tab.cut)
### - but what about effect size threshold???

# all in the proper direction
upRegLabeled$validated <- sapply(upRegLabeled$key, function(x) ifelse((!x %in% sig.keys.in.both), "NA" , x %in% rownames(lm17.tab.cut)))
downRegLabeled$validated <- sapply(downRegLabeled$key, function(x) ifelse((!x %in% sig.keys.in.both), "NA" , x %in% rownames(lm17.tab.cut)))
table(upRegLabeled$validated) # 71 true, 19 false, 2 NA
table(downRegLabeled$validated) # 88 true, 24 false, 3 NA

write.csv(upRegLabeled, file="../results/up_regulated_v0.csv", row.names=FALSE, quote=FALSE)
write.csv(downRegLabeled, file="../results/down_regulated_v0.csv", row.names=FALSE, quote=FALSE)

```

```{r}
# make a heatmap, other plots

# forest plots
forestPlot(metaObj, "1576")
forestPlot(metaObj, "6580")

```

Redo analysis with:
1) discovery/validation breakdown - 10 discovery, 6 validation
2) effect size filter

```{r}

# how does the validation work??? 
# I don't think this even makes sense as a todo item...

discoveryStudies <- c(1:8, 15, 16) # justification - I want the largest 
validationStudies <- c(9:14)
metaObj2 <- list()
metaObj2$originalData <- resListMI[discoveryStudies]
checkDataObject(metaObj2, "Meta", "Pre-Analysis")

metaObj2v <- list()
metaObj2v$originalData <- resListMI[validationStudies]
checkDataObject(metaObj2v, "Meta", "Pre-Analysis")

metaObj2 <- runMetaAnalysis(metaObj2)
metaObj2v <- runMetaAnalysis(metaObj2v)


# this is erroring out - it cannot find meta.summaries anymore :/ 
str(metaObj2, max.level=2)
metaObj2 <- filterGenes(metaObj2, isLeaveOneOut=TRUE, effectSizeThresh = 0.3, FDRThresh = 0.05) # arbitrarily chose effect size threshold
# what does the leave-one-out-analysis show?
 
filterRes2 <-summarizeFilterResults(metaObj2, getMostRecentFilter(metaObj2))

# this is trivial but it works
violinPlot(metaObj2$filterResults$FDR0.05_es0_nStudies1_looaTRUE_hetero0, metaObj2v$originalData$GSE89632, labelColumn = 'sexLabels')
violinPlot(metaObj2$filterResults$FDR0.05_es0_nStudies1_looaTRUE_hetero0, metaObj2v$originalData$GSE32504, labelColumn = 'sexLabels')
violinPlot(metaObj2$filterResults$FDR0.05_es0_nStudies1_looaTRUE_hetero0, metaObj2v$originalData$GSE33116, labelColumn = 'sexLabels')
violinPlot(metaObj2$filterResults$FDR0.05_es0_nStudies1_looaTRUE_hetero0, metaObj2v$originalData$GSE33814, labelColumn = 'sexLabels')
violinPlot(metaObj2$filterResults$FDR0.05_es0_nStudies1_looaTRUE_hetero0, metaObj2v$originalData$GSE48452, labelColumn = 'sexLabels')

### validation
metaObj2v <- filterGenes(metaObj2v, isLeaveOneOut=TRUE, effectSizeThresh=0.3, FDRThresh = 0.05)
#filterRes2v <-summarizeFilterResults(metaObj2v, getMostRecentFilter(metaObj2v))


# then only look at the genes of interest - maybe should have filtered before running meta-analysis

#  --> deeper dive into this
# the issue that I have with this is that "validation" is helpful for if we're going to use for classification
# -- but generally, just a one of
validMeta <- metaObj2v$metaAnalysis$pooledResults

## what do we define as a hit? (51+35)
validMeta[rownames(validMeta) %in% rownames(filterRes2$neg) & validMeta$effectSize < -0.3 & validMeta$fisherFDRDown < 0.05, c(1:3, ncol(validMeta)) ] # 36 out of 44 (28 at FDR threshold)
validMeta[rownames(validMeta) %in% rownames(filterRes2$pos) & validMeta$effectSize > 0.3 & validMeta$fisherFDRUp < 0.05,c(1:3, (ncol(validMeta)-3))] # 26 out of 26 (21 at FDR threshold)
## - why doesn't this match up with the summarization in filterRes2v?

```