---
title: "TestDEAP.Rmd"
author: "E Flynn"
date: "5/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Attempting to install - note it does NOT work to install from source - you need to use devtools.
```{r}
install.packages('pheatmap')

require('devtools')
setwd("~/Documents/EMILY/Stanford/Lab/AltmanLab/spring2018/liver_project/resources_from_winn/")
install_local("metaintegrator_public")
install.packages("deapathways_1.0.tar.gz",type="source", repos=NULL)
```


```{r}
require('MetaIntegrator')
data(tinyMetaObject)
#deapTest <- pathwayAnalysis(tinyMetaObject, numShuffles=100)
# - issue the gene names need to be mapped
# options: "uniprot" or "geneName"

# map gene names to symbol 
json.df2 <- json.df[json.df$key %in% rownames(metaObj$metaAnalysis$datasetEffectSizes),]
key.to.gene <- (split(json.df2$gene, json.df2$key))
newRowNames <- sapply(rownames(metaObj$metaAnalysis$datasetEffectSizes), function(x) key.to.gene[[as.character(x)]])
rownames(metaObj$metaAnalysis$datasetEffectSizes) <- sapply(newRowNames, as.character)

#deapTest2 <- pathwayAnalysis(metaObj, numShuffles=100)
deapTest3 <- pathwayAnalysis(metaObj, numShuffles=1000)
save(deapTest3, file="deapTest.RData")
```


